[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "1.3.1"
tag_format = "$version"
version_files = ["pyproject.toml"]

[tool.ruff.lint]
select = ['F', 'E', 'W', 'B']
ignore = ['E501', 'E701']

[tool.pyright]
include = ['src']
venvPath = '.'
venv = '.venv'
typeCheckingMode = 'standard'
useLibraryCodeForTypes = true

[tool.pdm.dev-dependencies]
dev = [
    "flake8",
    "commitizen",
    "pre-commit",
    "matplotlib",
    "twine",
    "pyright>=1.1.324",
]

[tool.mypy]
mypy_path = "typings"
ignore_missing_imports = true

[project]
name = "rlevaluation"
version = "1.3.1"
description = ""
authors = [
    {name = "Andy Patterson", email = "andnpatterson@gmail.com"},
]
dependencies = [
    "pandas>=1.5.3",
    "numba>=0.57.0",
    "numpy>=1.23.5",
    "scipy>=1.9.3",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pip",
    "ruff",
    "commitizen",
    "pre-commit",
    "matplotlib",
    "pyright>=1.1.324",
]
