name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    # setup the repository
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install uv
        uv pip compile --extra=dev pyproject.toml -o requirements.txt
        uv pip sync requirements.txt

    - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./scripts/run_tests.sh
